.PHONY: all clean test
SAMTOOLDIR=<insert samtools root dir>
SEQANDIR=seqan_library/
BOOST=<insert boost 1.45 root dir>

CXX= g++
CPPFLAGS= -D_IOLIB=2 -DMINREADS=2 # -DLOGDEBUG -g -DNDEBUG -DMMTEST
CXXFLAGS= -I$(SAMTOOLDIR) -I$(SEQANDIR) -I${BOOST} -I./ -Wno-deprecated  -O3
LDFLAGS= -L$(SAMTOOLDIR) -lbam -lz
SRCSHAPMUC=HapMuC.cpp Utils.cpp MutationModel.cpp HapBlock.cpp HaplotypeDistribution.cpp ObservationModelFB.cpp Haps.cpp Haps2.cpp EMBasic.cpp EMfor2.cpp MutationCall.cpp
OBJSHAPMUC=$(SRCSHAPMUC:%.cpp=%.o)
all: hapmuc
hapmuc:$(OBJSHAPMUC)
	$(CXX) -o $@ $(CXXFLAGS) $(HAPMUCFLAGS) $(OBJSHAPMUC) $(LDFLAGS)

clean:
	rm -f $(OBJSHAPMUC) $(OBJSCOMPAREVARIANTS)  $(OBJSMAKEGLF)
